### ISSUE TITLE
Outdated Config Error

### ISSUE THREAD

**Issue by tuxymuxy** [FranciscoDadone/StaffChatLite-Bungeecord#1]
Hi, So i get the following error using Waterfall on my server! 

> 07:44:14 [INFO] [StaffChatLite] Config outdated! (discord-staff-channel-id) Check the new config in: https://github.com/FranciscoDadone/StaffChatLite-Bungeecord/tree/master/src/main/resources
07:44:14 [WARNING] Error in dispatching command
java.lang.NumberFormatException: The specified ID is not a valid snowflake (Outdated config! Contact an administrator.). Expecting a valid long value!
    at net.dv8tion.jda.api.utils.MiscUtil.parseSnowflake(MiscUtil.java:123)
    at net.dv8tion.jda.api.utils.cache.SnowflakeCacheView.getElementById(SnowflakeCacheView.java:59)
    at net.dv8tion.jda.api.JDA.getTextChannelById(JDA.java:1822)
    at com.franciscodadone.staffchatlite.thirdparty.discord.DiscordHandler.sendMessage(DiscordHandler.java:38)
    at com.franciscodadone.staffchatlite.api.chat.ChatManager.sendStaffChatMessage(ChatManager.java:40)
    at com.franciscodadone.staffchatlite.commandmanager.commands.SCCommand.execute(SCCommand.java:24)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:207)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:157)
    at net.md_5.bungee.connection.UpstreamBridge.handleChat(UpstreamBridge.java:188)
    at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:150)
    at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:71)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by FranciscoDadone** [comment]
Hello, you can download the new config from here to update it. https://github.com/FranciscoDadone/StaffChatLite-Bungeecord/tree/master/src/main/resources
